set_property PACKAGE_PIN W5 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

############################
# 7 segment display        #
############################
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]

set_property PACKAGE_PIN U16 [get_ports {L[15]}]
set_property PACKAGE_PIN E19 [get_ports {L[14]}]
set_property PACKAGE_PIN U19 [get_ports {L[13]}]
set_property PACKAGE_PIN V19 [get_ports {L[12]}]
set_property PACKAGE_PIN W18 [get_ports {L[11]}]
set_property PACKAGE_PIN U15 [get_ports {L[10]}]
set_property PACKAGE_PIN U14 [get_ports {L[9]}]
set_property PACKAGE_PIN V14 [get_ports {L[8]}]
set_property PACKAGE_PIN V13 [get_ports {L[7]}]
set_property PACKAGE_PIN V3 [get_ports {L[6]}]
set_property PACKAGE_PIN W3 [get_ports {L[5]}]
set_property PACKAGE_PIN U3 [get_ports {L[4]}]
set_property PACKAGE_PIN P3 [get_ports {L[3]}]
set_property PACKAGE_PIN N3 [get_ports {L[2]}]
set_property PACKAGE_PIN P1 [get_ports {L[1]}]
set_property PACKAGE_PIN L1 [get_ports {L[0]}]

set_property PACKAGE_PIN U17 [get_ports down]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports start]
set_property PACKAGE_PIN T18 [get_ports up]


set_property IOSTANDARD LVCMOS33 [get_ports {L[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {L[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports up]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets { clk }]
